"""Base strategy class - Abstract base for all trading strategies."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Any

from packages.domain.enums import Timeframe
from packages.strategies.contracts import StrategyConfig

if TYPE_CHECKING:
    from packages.domain.entities.candle import Candle
    from packages.market_data.contracts import TickerData


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""

    strategy_id: str
    symbol: str
    signal_type: str  # BUY, SELL, NEUTRAL
    strength: Decimal = Decimal("1.0")
    confidence: Decimal = Decimal("1.0")
    current_price: Decimal | None = None
    target_price: Decimal | None = None
    stop_loss: Decimal | None = None
    take_profit: Decimal | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=datetime.utcnow)


class BaseStrategy(ABC):
    """Abstract base class for trading strategies.

    Strategies analyze market data and generate trading signals.
    They should never directly interact with exchanges or execute orders.

    The strategy lifecycle:
    1. Initialize with config
    2. Update with market data (candles, ticks)
    3. Generate signals when conditions are met
    4. Reset for next evaluation
    """

    def __init__(self, config: StrategyConfig) -> None:
        """Initialize strategy with configuration.

        Args:
            config: Strategy configuration
        """
        self.config = config
        self._is_enabled = False
        self._candles: dict[str, list[Candle]] = {}
        self._last_signal_time: datetime | None = None
        self._signals_generated = 0

    @property
    def id(self) -> str:
        """Get strategy ID."""
        return self.config.strategy_id

    @property
    def name(self) -> str:
        """Get strategy name."""
        return self.config.name

    @property
    def symbols(self) -> list[str]:
        """Get trading symbols."""
        return self.config.symbols

    @symbols.setter
    def symbols(self, value: list[str]) -> None:
        """Set trading symbols."""
        self.config.symbols = value

    @property
    def timeframe(self) -> Timeframe:
        """Get strategy timeframe."""
        return self.config.timeframe

    @property
    def parameters(self) -> dict[str, Any]:
        """Get strategy parameters."""
        return self.config.parameters

    @property
    def is_enabled(self) -> bool:
        """Check if strategy is enabled."""
        return self._is_enabled

    @property
    def last_signal_at(self) -> datetime | None:
        """Get timestamp of last generated signal."""
        return self._last_signal_time

    @property
    def signals_generated(self) -> int:
        """Get count of generated signals."""
        return self._signals_generated

    @property
    def signals_accepted(self) -> int:
        """Get count of signals accepted by risk management."""
        return 0

    @property
    def signals_rejected(self) -> int:
        """Get count of signals rejected by risk management."""
        return 0

    def enable(self) -> None:
        """Enable the strategy."""
        self._is_enabled = True

    def disable(self) -> None:
        """Disable the strategy."""
        self._is_enabled = False

    def update_candle(self, candle: Candle) -> None:
        """Update strategy with new candle data.

        Args:
            candle: New candle data
        """
        symbol = str(candle.symbol)
        if symbol not in self._candles:
            self._candles[symbol] = []

        self._candles[symbol].append(candle)

        # Keep only needed history
        max_candles = self.get_required_candles()
        if len(self._candles[symbol]) > max_candles:
            self._candles[symbol] = self._candles[symbol][-max_candles:]

    def update_ticker(self, ticker: TickerData) -> None:
        """Update strategy with ticker data.

        Args:
            ticker: New ticker data
        """
        # Override in subclasses if needed
        pass

    def get_candles(self, symbol: str) -> list[Candle]:
        """Get candles for a symbol.

        Args:
            symbol: Trading symbol

        Returns:
            List of candles.
        """
        return self._candles.get(symbol, [])

    def get_latest_candle(self, symbol: str) -> Candle | None:
        """Get the latest candle for a symbol.

        Args:
            symbol: Trading symbol

        Returns:
            Latest candle or None.
        """
        candles = self._candles.get(symbol, [])
        return candles[-1] if candles else None

    def evaluate(self) -> StrategySignal | None:
        """Evaluate the strategy and generate signal.

        This is called after market data is updated.
        Override this in subclasses to implement strategy logic.

        Returns:
            Signal if conditions are met, None otherwise.
        """
        if not self._is_enabled:
            return None

        signal = self._generate_signal()

        if signal:
            self._signals_generated += 1
            self._last_signal_time = datetime.utcnow()

        return signal

    @abstractmethod
    def _generate_signal(self) -> StrategySignal | None:
        """Generate trading signal based on indicators.

        Override this in subclasses to implement strategy logic.

        Returns:
            Signal if conditions are met, None otherwise.
        """
        ...

    @abstractmethod
    def get_required_candles(self) -> int:
        """Get number of candles needed for strategy.

        Override to specify how much history the strategy needs.

        Returns:
            Number of candles needed.
        """
        ...

    def reset(self) -> None:
        """Reset strategy state."""
        self._candles.clear()
        self._last_signal_time = None

    def __str__(self) -> str:
        """String representation."""
        return f"{self.__class__.__name__}({self.id}, {self.name})"
